-- ================================================
-- Template generated from Template Explorer using:
-- Create Procedure (New Menu).SQL
--
-- Use the Specify Values for Template Parameters 
-- command (Ctrl-Shift-M) to fill in the parameter 
-- values below.
--
-- This block of comments will not be included in
-- the definition of the procedure.
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Jeremy Wolfe
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE jawolf7279.Buy_Vehicle 
@CUSTOMERNAME VARCHAR(50),
@CUSTOMEREMAIL VARCHAR(50),
@CUSTOMERADDRESS1 VARCHAR(100),
@CUSTOMERADDRESS2 VARCHAR(50),
@CUSTOMERCITY VARCHAR(20),
@CUSTOMERSTATE VARCHAR(30),
@CUSTOMERZIP INT,
@CARYEAR INT,
@CARMAKE VARCHAR(50),
@CARMODEL VARCHAR(50),
@CARVIN VARCHAR(17),
@DEALERNUMBERTOADD INT,
@BUYINGPRICEOFUNIT MONEY


AS
BEGIN

SET @CUSTOMERNAME  =  lower (@CUSTOMERNAME);
SET @CUSTOMEREMAIL  =  lower (@CUSTOMEREMAIL);
SET @CUSTOMERADDRESS1 =  lower (@CUSTOMERADDRESS1);
SET @CUSTOMERADDRESS2  =  lower (@CUSTOMERADDRESS2);
SET @CUSTOMERCITY  =  lower (@CUSTOMERCITY);
SET @CUSTOMERSTATE  =  lower (@CUSTOMERSTATE);
SET @CARMAKE  =  lower (@CARMAKE);
SET @CARMODEL  =  lower (@CARMODEL);
SET @CARVIN  =  UPPER (@CARVIN);



	DECLARE @CUSTOMER_ID INT;

	-- ADD CUSTOMER INFO FOR PURCHACING
	INSERT INTO JAWOLF7279.CUSTOMER(CUSTOMER_NAME,EMAIL_ADDRESS, ADDRESS1, ADDRESS2, CITY, [STATE], ZIP)
	VALUES (@CUSTOMERNAME,@CUSTOMEREMAIL,@CUSTOMERADDRESS1,@CUSTOMERADDRESS2,@CUSTOMERCITY,@CUSTOMERSTATE,@CUSTOMERZIP);

	SET @CUSTOMER_ID = (select SCOPE_IDENTITY());

	--ADD VEHICLE TO LIST OF VEHICLES
	INSERT INTO JAWOLF7279.VEHICLE(MAKE, MODEL, YEAR, VIN)
	VALUES (@CARMAKE, @CARMODEL,@CARYEAR, @CARVIN);

	-- ADD VEHICLE TO INVENTORY
	INSERT INTO JAWOLF7279.DEALER_INVENTORY(VEHICLE_ID, DEALER_ID, ISONHAND)
	VALUES ((select SCOPE_IDENTITY()), @DEALERNUMBERTOADD, 1)

	--ADD TRANSACTION 
	SET @BUYINGPRICEOFUNIT = (@BUYINGPRICEOFUNIT * -1)
	INSERT INTO JAWOLF7279.TRANSACTIONS(CUSTOMER_ID, INVENTORY_ID, TRANSACTION_AMT)
	VALUES (@CUSTOMER_ID,(SELECT SCOPE_IDENTITY()),@BUYINGPRICEOFUNIT);

END
GO
