SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Jeremy Wolfe
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE JAWOLF7279.Pay_Loan 

@LOAN_ID INT,
@PAYMENT_AMOUNT MONEY,
@PAYMENT_TYPE VARCHAR(10)

AS
BEGIN
DECLARE @LOAN_TOTAL MONEY = (SELECT CURR_PRINC_AMT FROM JAWOLF7279.LOAN WHERE LOAN_ID = @LOAN_ID);
DECLARE @RATE FLOAT = (SELECT APR_RATE FROM JAWOLF7279.LOAN WHERE LOAN_ID = @LOAN_ID);
DECLARE @MIN_PAYMENT MONEY = (SELECT MIN_PAYMENT FROM JAWOLF7279.LOAN WHERE LOAN_ID = @LOAN_ID);
DECLARE @FUTURE_VALUE MONEY = (select* from jawolf7279.FUTURE_VALUE(@RATE,@PAYMENT_AMOUNT,@LOAN_TOTAL));

IF (@PAYMENT_AMOUNT < @LOAN_TOTAL AND @MIN_PAYMENT <= @PAYMENT_AMOUNT)
BEGIN



--INSERT THE TRANSACTION
INSERT INTO JAWOLF7279.LOAN_PAYMENT(LOAN_ID, PAYMENT_METHOD, PAYMENT_AMOUNT)
	VALUES (@LOAN_ID, @PAYMENT_TYPE, @PAYMENT_AMOUNT);

--UPDATE CURR_PRINC_AMOUNT
UPDATE JAWOLF7279.LOAN
SET CURR_PRINC_AMT = (@FUTURE_VALUE)
WHERE LOAN_ID = @LOAN_ID;

--UPDATE MIN PAYMENT
UPDATE JAWOLF7279.LOAN
SET MIN_PAYMENT = (SELECT * FROM JAWOLF7279.CALC_PAYMENT(@FUTURE_VALUE,@RATE,(SELECT LOAN_LENGTH FROM JAWOLF7279.LOAN WHERE LOAN_ID = @LOAN_ID)));

END
END
GO
