SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Jeremy Wolfe
-- Create date: 
-- Description:	
-- =============================================
CREATE PROCEDURE jawolf7279.Sell_Vehicle 
	-- Add the parameters for the stored procedure here
@CUSTOMERNAME VARCHAR(50),
@CUSTOMEREMAIL VARCHAR(50),
@CUSTOMERPASSWORD VARCHAR(50),
@CUSTOMERADDRESS1 VARCHAR(100),
@CUSTOMERADDRESS2 VARCHAR(50),
@CUSTOMERCITY VARCHAR(20),
@CUSTOMERSTATE VARCHAR(30),
@CUSTOMERZIP INT,
@VEHICLEID INT,
@PRICEOFUNIT MONEY,
@LOANLEGNTH INT,
@APRRATE FLOAT

AS

BEGIN

SET @CUSTOMERNAME = LOWER (@CUSTOMERNAME);
SET @CUSTOMEREMAIL = LOWER (@CUSTOMEREMAIL) ;
SET @CUSTOMERPASSWORD = LOWER (@CUSTOMERPASSWORD) ;
SET @CUSTOMERADDRESS1 = LOWER (@CUSTOMERADDRESS1) ;
SET @CUSTOMERADDRESS2 = LOWER (@CUSTOMERADDRESS2);
SET @CUSTOMERCITY = LOWER (@CUSTOMERCITY) ;
SET @CUSTOMERSTATE = LOWER (@CUSTOMERSTATE); 



IF ((SELECT COUNT(INVENTORY_ID) FROM JAWOLF7279.DEALER_INVENTORY WHERE VEHICLE_ID = @VEHICLEID) = 1) AND ((SELECT ISONHAND FROM JAWOLF7279.DEALER_INVENTORY WHERE VEHICLE_ID = @VEHICLEID) = 1)
BEGIN


DECLARE @CUSTOMER_ID INT;
DECLARE @INVENTORYID INT;


SET @INVENTORYID = (SELECT INVENTORY_ID FROM JAWOLF7279.DEALER_INVENTORY WHERE VEHICLE_ID = @VEHICLEID);

--ADD CUSTOMER INTO TABLE
INSERT INTO JAWOLF7279.CUSTOMER(CUSTOMER_NAME, Email_Address, ADDRESS1, ADDRESS2, CITY, [STATE], ZIP)
VALUES (@CUSTOMERNAME,@CUSTOMEREMAIL,@CUSTOMERADDRESS1,@CUSTOMERADDRESS2,@CUSTOMERCITY,@CUSTOMERSTATE,@CUSTOMERZIP);
SET @CUSTOMER_ID = (SELECT SCOPE_IDENTITY());

--GIVE CUSTOMER ONLINE ACCESS TO PAY ON LOAN
INSERT INTO JAWOLF7279.USERS(CUSTOMER_ID, [USER_NAME], PASSWORD_HASH, ISACTIVATED)
	VALUES (@CUSTOMER_ID, @CUSTOMEREMAIL, HASHBYTES('MD5', @CUSTOMERPASSWORD),1)

-- MODIFY VEHICLE IN INVENTORY
UPDATE JAWOLF7279.DEALER_INVENTORY
SET ISONHAND = 0
WHERE VEHICLE_ID = @VEHICLEID;

-- FLOOR LOAN
DECLARE @MINPAYMENT MONEY;
SET @MINPAYMENT = (select * from calc_payment(@PRICEOFUNIT, @APRRATE, @LOANLEGNTH));
INSERT INTO JAWOLF7279.LOAN(CUSTOMER_ID, VEHICLE_ID, LOAN_AMOUNT, APR_RATE, LOAN_LENGTH, MIN_PAYMENT, CURR_PRINC_AMT)
	VALUES(@CUSTOMER_ID,@VEHICLEID,@PRICEOFUNIT,@APRRATE,@LOANLEGNTH,@MINPAYMENT,@PRICEOFUNIT);

--ADD TRANSACTION 
INSERT INTO JAWOLF7279.TRANSACTIONS(CUSTOMER_ID, INVENTORY_ID, TRANSACTION_AMT)
	VALUES (@CUSTOMER_ID,@INVENTORYID,@PRICEOFUNIT);


END
END
GO
